sudo: required
language: rust
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache:
  directories:
    - $HOME/.cargo
env:
  - ELEFREN_FEATURES="--features toml"
  - ELEFREN_FEATURES="--features json"
  - ELEFREN_FEATURES="--features all"
  - ELEFREN_FEATURES=""
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test $ELEFREN_FEATURES
matrix:
  include:
    - name: "Coverage"
      rust: nightly
      before_cache: RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install -f cargo-tarpaulin
      script: cargo build --features all
      after_success: cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --features all

    - name: "rustfmt"
      rust: nightly
      before_script: rustup component add rustfmt-preview
      script: cargo fmt --all -- --check

  allow_failures:
    - rust: nightly
notifications:
  email:
    on_success: never
